### ISSUE TITLE
Fix:LINEログイン時に画面遷移するように修正

### ISSUE THREAD

**Issue by kubo-step** [mikako-40/grow_journey#35]
#### 質問内容・実現したいこと
LINEの登録・ログインボタンを押すと、LINEへリクエストが飛んでログインをすることができる。
#### 現状発生している問題・エラーメッセージ
手動でリロードすると画面遷移するのですが、自動的にLINE画面へ飛びません。
また手動でリロードした際、下記エラーが発生してログインに失敗する時があります。
[![Image from Gyazo](https://i.gyazo.com/08c653bf5fdbcc7c87c2d5006f65d932.gif)](https://gyazo.com/08c653bf5fdbcc7c87c2d5006f65d932)
[![Image from Gyazo](https://i.gyazo.com/34435360c864b4e961d815e0e7d0adc2.gif)](https://gyazo.com/34435360c864b4e961d815e0e7d0adc2)

[![Image from Gyazo](https://i.gyazo.com/02b0c9c8154e7857b977b7e3c09c2042.png)](https://gyazo.com/02b0c9c8154e7857b977b7e3c09c2042)
#### どの処理までうまく動いているのか
リロードした際に、ログインできる時もあります。

#### 該当のソースコード
app/javascript/line_login.js
```
document.addEventListener('DOMContentLoaded', () => {
  // csrf-tokenを取得
  const token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
  const LIFF_ID = gon.liff_id;

  liff
  .init({
    liffId: LIFF_ID,
    withLoginOnExternalBrowser: true
  })
    // 初期化後の処理の設定
  liff
  .ready.then(() => {
    const idToken = liff.getIDToken()
    // bodyにパラメーターの設定
    const body =`idToken=${idToken}`
    // リクエスト内容の定義
    const request = new Request('/users', {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
        'X-CSRF-Token': token
      },
      method: 'POST',
      body: body
    });

    // リクエストを送る
    fetch(request)
    // jsonでレスポンスからデータを取得して/goalsに遷移する
    .then(response => response.json())
    .then(data => {
      data_id = data
    })
    .then(() => {
      window.location = '/goals'
    })
    .catch((err) => {
      console.log(err);
    })
  })
});
```
app/javascript/aplication.js
```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import { Turbo } from "@hotwired/turbo-rails"
Turbo.session.drive = false
import "controllers";
import "modal";
import "line_login";
```

#### エラーから考えられる原因
ログインできる時もあるので、Javascript自体のコードが悪いというより、
読み込みに関するコードがどこかが間違っているのではないかと思います。

#### 試したこと
Turboが関連しているのかと下記の通り記述を変更してみましたが、特に変わりありませんでした。
```
import { Turbo } from "@hotwired/turbo-rails"
Turbo.session.drive = false
```
お手数ですが、ご助言いただけますと幸いです。
よろしくお願いいたします。

**Comment by kenchasonakai** [comment]
DomcontentLoadedがturbo関連で動いてないのかもですね、turboオフの状態で画面遷移するようにするor turbo用のJS発火イベントを使用するなど試してみるといいかもです

https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/event

**Comment by kubo-step** [comment]
コメントありがとうございます。
ずっとjavascriptの方を気にしており、DomcontentLoadedをturbo:loadにしてみてもうまくいかなかったのですが、
『turboオフの状態で画面遷移するようにする』をヒントに、
リンクに`data:{turbo:false}`を付与することで解決いたしました！
```
<%= link_to '（LINE）ユーザー登録・ログイン', new_user_path, class: 'btn btn-success btn-lg', data:{turbo: false} %>
```
ありがとうございました。
