### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [mikako-40/grow_journey#72]
LGTMです！
このissueのコメントで本リリースまでのスケジュールの返答をお願いします
綺麗に作れている印象でした
以下にレビュー詳細を記載します

## 目標・タスク
目標とタスクが同じ扱いになってしまっているように感じるので、目標に紐づく形でタスクを登録出来て、全て達成すると目標が達成できるようにするなど親子関係のようにするなどの工夫があると良いかなと感じました

## 画面について
細かいところなのですが、表示が隠れてしまっていたり、マージンが設定されていないのか要素がくっついてしまっているところがあったので優先度は低いと思いますが後々改善できると良いですね
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/adecfcc75a43fd6cf11492d8bec80516.png)](https://startup-technology.gyazo.com/adecfcc75a43fd6cf11492d8bec80516)

## 機能面について
成長にフォーカスしたアプリだと思うので、振り返りを促したりとかもっと成長を実感できるような機能を追加すると厚みが出てくるかなと思いました

**Comment by kubo-step** [comment]
レビューありがとうございます。

おっしゃる通り、目標とタスクは分けたいと思います。
またご褒美機能を取りやめ、下記機能を実装したいと思います。
レイアウト微調整も含めて、本リリースは1/6の予定です。

- 目標とタスクの切り分け(1週間)
  - 目標の進捗表示(目標に紐づけたタスクの完了数によって、進捗を管理する)
     - 例：目標（タスク4件中２件完了）進捗50%のバーの表示
  - タスクが全て完了したら、目標も達成とする
  - タスクにかかった時間を手動で入力可能とする

- 振り返りページの作成(1週間)
  -  週間と月間で表示を切り替えられる
  -  カレンダービューで記録のあった日を確認できる
  -  指定された期間の中の達成した目標・タスクの数を表示し、カテゴリ別に円で色分け表示する(グラフ)
  -  目標とタスクの達成の進捗を表示
  -  タスクの取り組み時間の表示(グラフ)

- SNS共有機能の強化(3日)
  - OGP画像の生成
  - 文言の変更(目標やタスクの内容にして、学習記録などが出来るようにする)

- 応援機能の実装(3日)
  - 目標・タスクの公開設定を実装
  - 他のユーザーに応援ボタンを押せる

**Comment by kenchasonakai** [comment]
承知しました！
引き続き開発頑張ってください！
